spring.application.name=BankAppBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=bankappdatabase
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.key = c195a485f31f4176068d426e0e758baf
